export const COLLECTIONS = {
  users: "users",
  schools: "schools",
  academicYears: "academicYears",
  classes: "classes",
  subjects: "subjects",
  studentProfiles: "studentProfiles",
  teacherProfiles: "teacherProfiles",
  parentProfiles: "parentProfiles",
  parentStudents: "parentStudents",
  teacherClasses: "teacherClasses",
  teacherSubjects: "teacherSubjects",
  attendance: "attendance",
  homework: "homework",
  homeworkSubmissions: "homeworkSubmissions",
  homeworkTutorSessions: "homeworkTutorSessions",
  grades: "grades",
  reportCards: "reportCards",
  feeStructures: "feeStructures",
  feeInvoices: "feeInvoices",
  payments: "payments",
  messageThreads: "messageThreads",
  messages: "messages",
  notifications: "notifications",
  broadcasts: "broadcasts",
  auditLogs: "auditLogs",
  timetablePeriods: "timetablePeriods",
  exams: "exams",
  examResults: "examResults",
  books: "books",
  libraryIssues: "libraryIssues",
  transportRoutes: "transportRoutes",
  transportAssignments: "transportAssignments",
  leaveRequests: "leaveRequests",
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
