import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#1e293b",
  },
  header: {
    marginBottom: 24,
    borderBottom: "2 solid #6366f1",
    paddingBottom: 12,
  },
  schoolName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#6366f1",
  },
  title: {
    fontSize: 14,
    marginTop: 4,
    color: "#64748b",
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#6366f1",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottom: "1 solid #e2e8f0",
  },
  narrative: {
    lineHeight: 1.5,
    color: "#334155",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 9,
    color: "#94a3b8",
  },
});

export type ReportCardPdfData = {
  schoolName: string;
  studentName: string;
  className: string;
  term: string;
  academicYear: string;
  aiSummary: string;
  teacherRemarks?: string | null;
  subjectGrades: { subject: string; score: number; grade?: string }[];
  attendancePct: number;
  homeworkCompletionPct: number;
};

export function ReportCardDocument({ data }: { data: ReportCardPdfData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.schoolName}>{data.schoolName}</Text>
          <Text style={styles.title}>Report Card — {data.term} ({data.academicYear})</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Student Information</Text>
          <Text>Name: {data.studentName}</Text>
          <Text>Class: {data.className}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Subject Grades</Text>
          {data.subjectGrades.map((g) => (
            <View key={g.subject} style={styles.row}>
              <Text>{g.subject}</Text>
              <Text>
                {g.score}% {g.grade ? `(${g.grade})` : ""}
              </Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Overview</Text>
          <Text>Attendance: {data.attendancePct}%</Text>
          <Text>Homework Completion: {data.homeworkCompletionPct}%</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Teacher&apos;s Comments</Text>
          <Text style={styles.narrative}>{data.aiSummary}</Text>
          {data.teacherRemarks ? (
            <Text style={[styles.narrative, { marginTop: 8 }]}>{data.teacherRemarks}</Text>
          ) : null}
        </View>

        <Text style={styles.footer}>Generated by ScholarOS • {new Date().toLocaleDateString()}</Text>
      </Page>
    </Document>
  );
}
